version: '3.0.0'
services:
  web:
    build: ./RadioShop
    container_name: ${WEB_HOST}
    ports:
      # - "${WEB_PORT}:${WEB_PORT}"
      - "80:80"
    environment:
      # - ConnectionStrings__DefaultConnection="Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      # - JWT__SigningKey="${JWT_SECRET_KEY}"
      - PORT=${WEB_PORT}
      - HOST=${WEB_HOST}
      # - ASPNETCORE_URLS=http://localhost:8080
      - HTTP_PORTS=8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5